### ISSUE TITLE
CI is silently failing

### ISSUE THREAD

**Issue by sebastianrosik** [fadehelix/narcoticmd#14]
Hi, check this latest build for example: https://travis-ci.org/fadehelix/narcoticmd/builds/329109962
Tests are failing, but the job exits with code 0, so this failing job in Travis is marked as passed.

**Comment by fadehelix** [comment]
@sebastianrosik thanks for report. I finally solved this issue by eject CRA. It's a first time in my juorney with CRA and react-script when I had to do this.
Now, when I run Jest explicitly, build is going to be red when any test fail.
